[pytest]
addopts = 
    -v
    --html=test-reports/html-report/report.html
    --self-contained-html

markers =
    smoke: Smoke tests
    regression: Regression tests
    ui: UI tests
    api: API tests
    critical: Critical business flow